### ISSUE TITLE
No NextAuth found +Server forbidden access+ not allow to login now

### ISSUE THREAD

**Issue by NV3S** [lyc8503/EasierConnect#11]
登录需要TOTP，但到如下错误就退出了

```
2023/01/24 11:11:41 Login Request: https://serveradd:port/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs
2023/01/24 11:11:41 No NextAuth found.
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
EasierConnect/core.WebLogin({0xc0000a2540?, 0x2?}, {0xc00009e100, 0x5}, {0xc00009e150, 0x10})
        EasierConnect/core/web_login.go:142 +0x162d
EasierConnect/core.(*EasyConnectClient).Login(0xc0000c1ef0, {0xc00009e100?, 0xc0000c1e90?}, {0xc00009e150?, 0x2?})
        EasierConnect/core/EasyConnectClient.go:35 +0x91
main.main()
        EasierConnect/main.go:38 +0x5bb
2023/01/24 11:11:41 Login FAILED: <?xml version="1.0" encoding="utf-8"?>
<Auth>
        <LBEnabled>1</LBEnabled>
        <CSRF_RAND_CODE>CODEHERE</CSRF_RAND_CODE>
        <AuthInfo><![CDATA[]]></AuthInfo>
        <Note><![CDATA[Server forbidden access!]]></Note>
        <ErrorCode>20113</ErrorCode>
        <Result>0</Result>
        <Message><![CDATA[not allow to login now]]></Message>
</Auth>
```

**Comment by supernova4869** [comment]
我也是这个问题

**Comment by lyc8503** [comment]
不太清楚提交 TOTP 的请求格式, 也不太方便测试, 需要方便测试的人修改后 PR.

**Comment by supernova4869** [comment]
> 不太清楚提交 TOTP 的请求格式, 也不太方便测试, 需要方便测试的人修改后 PR.

我如果把原版的EasyConnect搞来，然后抓包拿到发送的请求，加到源码的发送请求的逻辑那里是不是可以（没用过Go），还需要其他的吗

**Comment by lyc8503** [comment]
登录部分可以在浏览器 F12 中比较容易的看到, 可以对比一下 `web_login.go` 的登录逻辑, 看看请求的差异.

**Comment by lyc8503** [comment]
有人 PR 了 TOTP 相关的登录方式, 方便的话可以测试一下 [TestBuild14](https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild14) 是否解决了该问题.

**Comment by dwdcth** [comment]
测试 TestBuild14 TOTP 成功登录
![image](https://user-images.githubusercontent.com/1883728/217707975-591cc9dc-11c6-4bb9-89af-9c708c2902d3.png)

**Comment by lyc8503** [comment]
感谢你的测试!
