### ISSUE TITLE
Unexpected SMS Response

### ISSUE THREAD

**Issue by Heartfirey** [lyc8503/EasierConnect#12]
When using cli to connect to `https://vpn.jxnu.edu.cn:443`, I failed to log in and got the following return message.

```bash
2023/01/24 18:28:25 Login Request: https://vpn.jxnu.edu.cn:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs
2023/01/24 18:28:26 SMS code required.
2023/01/24 18:28:26 SMS Request: https://vpn.jxnu.edu.cn:443/por/login_sms.csp?apiversion=1
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
EasierConnect/core.WebLogin({0xc00001c660?, 0x2?}, {0xc000024130, 0xc}, {0xc000024180, 0x9})
        EasierConnect/core/web_login.go:125 +0x1205
EasierConnect/core.(*EasyConnectClient).Login(0xc00007fef0, {0xc000024130?, 0xc00007fe90?}, {0xc000024180?, 0x2?})
        EasierConnect/core/EasyConnectClient.go:35 +0x91
main.main()
        EasierConnect/main.go:38 +0x5bb
2023/01/24 18:28:26 unexpected sms resp: <?xml version="1.0" encoding="utf-8"?>
<Auth>
        <SmsSendInterval>0</SmsSendInterval>
        <IS_IN_PERIOD>1</IS_IN_PERIOD>
        <T_SMSTITLE></T_SMSTITLE>
        <ISLBENABLED>0</ISLBENABLED>
        <T_SMSINFOR></T_SMSINFOR>
        <Message><![CDATA[auth result.]]></Message>
        <USER_PHONE>151****7528</USER_PHONE>
        <SMS_INTERVAL>0</SMS_INTERVAL>
        <CURRENT_PHONE></CURRENT_PHONE>
        <CompatData><![CDATA[
var g_DisableTime ="0";
var phone ="151****7528";
var smsApps ="HTTP";
]]></CompatData>
        <ErrorCode>1</ErrorCode>
        <SMS_SENDTYPE>HTTP</SMS_SENDTYPE>
</Auth>
```

**Comment by lyc8503** [comment]
Did you actually receive the SMS code after the error?

**Comment by Heartfirey** [comment]
> Did you actually receive the SMS code after the error?

Yes, I could receive the SMS code normally. But while I run it again, I get the same error.

Here is my runtime environment:

`Windows 11 Professional 22623.1180` `AMD64` `Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz 2.59 GHz`

I run this program using powershell, here is the environment information:

```bash
Name                           Value
----                           -----
PSVersion                      5.1.22621.1037
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1037
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Here are the command I executed:

```bash
.\EasierConnect.exe -server vpn.jxnu.edu.cn -port 443 -username <...> -password <...>
```

If you needed, I can provide remote reproduction for this problem.

**Comment by lyc8503** [comment]
Please try https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild10

**Comment by Heartfirey** [comment]
> Please try https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild10

Thank you! Now it works properly!
