### ISSUE TITLE
Error occurred while recv, retrying: EOF panic: recv retry limit exceeded.

### ISSUE THREAD

**Issue by Howard0x3f** [lyc8503/EasierConnect#18]
你好，当我运行时显示如下信息。

```
Error occurred while recv, retrying: EOF
panic: recv retry limit exceeded.

goroutine 36 [running]:
EasierConnect/core.StartProtocol.func1()
        EasierConnect/core/protocol.go:196 +0x105
created by EasierConnect/core.StartProtocol
        EasierConnect/core/protocol.go:199 +0xd2
```

**Comment by lyc8503** [comment]
你使用的是哪个 EasierConnect 版本?

**Comment by Howard0x3f** [comment]
11

**Comment by Howard0x3f** [comment]
> 你使用的是哪个 EasierConnect 版本?

11

**Comment by lyc8503** [comment]
看起来和 #10 比较类似, 但在 TestBuild 11 中应该已经修复了, 能否提供更多信息. (比如是启动后多久出现的 EOF? 能否稳定复现? 使用的 EasyConnect 版本等.)

**Comment by Howard0x3f** [comment]
> 
启动后大概一分钟出现EOF;
能够稳定复现；
我的电脑中没有安装EasyConnect，我们学校官网上下载的EasyConnect是7.6.7.0。
