### ISSUE TITLE
panic: runtime error: slice bounds out of range [:486] with capacity 64

### ISSUE THREAD

**Issue by cxsunflower** [lyc8503/EasierConnect#19]
[TestBuild11](https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild11)
连接成功后打开的第一个网页正常，但是打开第二个网页就出现问题了
```
2023/01/25 15:07:41 recv: read 1400 bytes
00000000  45 00 05 78 09 11 40 00  3e 06 17 e7 c0 a8 fd 33  |E..x..@.>......3|
00000010  c0 a8 98 03 00 50 4c a0  a5 18 8f 2a 2e 7e 9e 6c  |.....PL....*.~.l|
00000020  80 10 00 7a 45 50 00 00  01 2023/01/25 15:07:41 send: wrote 52 bytes
01 08 0a 51 1c 6e 32  |...zEP......Q.n2|
00000030  b0 76 06 d1 a8 78 f5 91  7e 9e ea 7a a9 eb 22 0e  |.v...x..~..z..".|
00000040  6f fd 3d panic: runtime error: slice bounds out of range [:486] with capacity 64

goroutine 27 [running]:
EasierConnect/core.BlockTXStream.func1({0xc00002be80, 0xb8ecc0?, 0x40})
        EasierConnect/core/protocol.go:179 +0x157
EasierConnect/core.(*EasyConnectEndpoint).WritePackets(0xc000132210, {{0xc000122380, 0x1, 0x1}})
        EasierConnect/core/tun_stack.go:62 +0xdc
gvisor.dev/gvisor/pkg/tcpip/stack.(*delegatingQueueingDiscipline).WritePacket(0xc00011e310, 0xc000002000)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/nic.go:152 +0xa2
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writeRawPacket(0xc00017ac00, 0xc000002000)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/nic.go:396 +0x39
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writePacket(0xc00017ac00, 0x4?)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/nic.go:392 +0x3d
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).WritePacket(0xc00017ac00, 0xc000000564?, 0xc000002000)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/nic.go:353 +0x1cd
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).writePacketPostRouting(0xc000334000, 0xc000646000, 0xc000002000, 0x0?)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/network/ipv4/ipv4.go:560 +0x2f0
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).writePacket(0xc000334000, 0x0?, 0x0?)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/network/ipv4/ipv4.go:510 +0x153
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).WritePacket(0x7bed20?, 0xc000646000, {0x800?, 0xa0?, 0x4c?}, 0xa518946e2e7e9e6c?)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/network/ipv4/ipv4.go:478 +0x85
gvisor.dev/gvisor/pkg/tcpip/stack.(*Route).WritePacket(0xc000646000, {0x41a3d0?, 0xc0?, 0x0?}, 0x4?)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/stack/route.go:468 +0x7f
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.sendTCP(0xc000646000, {{0x4ca0, {0xc00041a3d0, 0x4}, 0x50, {0xc00041a3ac, 0x4}}, 0x40, 0x0, 0x10, ...}, ...)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/connect.go:911 +0x234
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendTCP(0xc000642000, 0x719da0?, {{0x4ca0, {0xc00041a3d0, 0x4}, 0x50, {0xc00041a3ac, 0x4}}, 0x40, 0x0, ...}, ...)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/connect.go:809 +0xe5
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendRaw(0xc000642000, 0x0?, 0x10, 0x2e7e9e6c, 0xa518946e, 0x3fd5)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/connect.go:978 +0x316
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).sendEmptyRaw(0xc000690360?, 0xe0?, 0x0?, 0x72d5c0?, 0x0?)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/connect.go:965 +0x9c
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendEmptySegment(0xc0006ce000, 0xd0?, 0x2e7e9e6c)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/snd.go:1696 +0x99
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendAck(...)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/snd.go:338
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).handleSegmentsLocked(0xc000642000)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/connect.go:1189 +0x159
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).handleConnected(0xc000642220?, 0xc000642000)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/dispatcher.go:192 +0x85
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0xc000312cf0, 0x0?)
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/dispatcher.go:312 +0x245
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        gvisor.dev/gvisor@v0.0.0-20220901235040-6ca97ef2ce1c/pkg/tcpip/transport/tcp/dispatcher.go:390 +0x13b

```

**Comment by lyc8503** [comment]
Thanks for @i-Pear's work.
