### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by aacc668** [lyc8503/EasierConnect#27]
服务端版本:未知
EasierConnect版本:13
连接过程中报错如下:
2023/01/27 21:42:39 Login Request: https://xxx:443/por/login_auth.csp?apiversion=1
2023/01/27 21:42:39 WARNING: No CSRF Code Match. Maybe you're connecting to an older server? Continue anyway...
2023/01/27 21:42:39 Login Request: https://xxxx:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs
2023/01/27 21:42:39 No NextAuth found.
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
EasierConnect/core.WebLogin({0xc000024618?, 0x2?}, {0xc00001c120, 0x8}, {0xc00001c170, 0xa})
        EasierConnect/core/web_login.go:149 +0x16de
EasierConnect/core.(*EasyConnectClient).Login(0xc000115ef0, {0xc00001c120?, 0xc000115e90?}, {0xc00001c170?, 0x2?})
        EasierConnect/core/EasyConnectClient.go:35 +0x91
main.main()
        EasierConnect/main.go:39 +0x5bb
2023/01/27 21:42:39 Login FAILED: <?xml version="1.0" encoding="utf-8"?><Auth><Result>0</Result> <EnableMAM>1</EnableMAM><SuportMDM>0</SuportMDM><CurAuth>1</CurAuth><NextAuth>-1</NextAuth><AuthInfo><![CDATA[]]></AuthInfo><Note><![CDATA[The characters are incorrect or has expired!]]></Note><ChallengeMsg><![CDATA[]]></ChallengeMsg><SmsIsStillValid>0</SmsIsStillValid><Phone><![CDATA[]]></Phone><CurPhone><![CDATA[]]></CurPhone><SmsSendType><![CDATA[default]]></SmsSendType><mdmEnable>0</mdmEnable><mdmUqid></mdmUqid><MdmUrl>https://:0</MdmUrl><RootRule>-1</RootRule></Auth>

可能是需要输入图形验证码的原因吗?原版EasyConnect每次登录需要输入验证码
![image](https://user-images.githubusercontent.com/74100166/215103955-c4c1f648-5477-4030-9b65-02f28f0f98e6.png)

**Comment by githuu5y5u** [comment]
验证码的路径: https://vpn.niubidaxue.edu.cn/por/rand_code.csp
https://github.com/lyc8503/EasierConnect/blob/7a1dc4260786d22c2cdc852ce66dcbe55eb2e6a7/core/web_login.go#L92

**Comment by lyc8503** [comment]
我使用的 VPN 是在多次登录失败后才会出现验证码, 验证码这里不太好处理, 这种验证码虽然可以被轻松识别但涉及到滥用问题, 让人工介入输入验证码的话比较繁琐, 请等待即将合并的直接使用网页登录的 ECAgent 登录方式.
