### ISSUE TITLE
M7.6.8R2 panic: Login FAILED:

### ISSUE THREAD

**Issue by 0neday** [lyc8503/EasierConnect#5]
product: sanfor SSL VPN
version： M7.6.8R2
````
2023/01/23 08:28:55 Login Request: https://xxxxxxxxxx.com/por/login_psw.csp?anti_replay=1&encrypt=1
panic: Login FAILED: <?xml version="1.0" encoding="utf-8"?>
<Auth>
        <LBEnabled>0</LBEnabled>
        <Message><![CDATA[password auth success]]></Message>
        <Result>1</Result>
        <TwfID>4e2025688d4b4810</TwfID>
        <pwpErrorCode>0</pwpErrorCode>
        <ErrorCode>1</ErrorCode>
        <CurAuth>1</CurAuth>
        <CSRF_RAND_CODE>1589546080</CSRF_RAND_CODE>
        <EnableMAM>0</EnableMAM>
        <IsFirstAuth>1</IsFirstAuth>
        <AuthInfo><![CDATA[]]></AuthInfo>
</Auth>


goroutine 1 [running]:
main.WebLogin()
        EasierConnect/web_login.go:103 +0x20e5
main.main()
        EasierConnect/protocol.go:119 +0x45

**Comment by lyc8503** [comment]
请问你登录时使用的认证方法是什么, 是只要账号密码登录吗?

**Comment by sky96111** [comment]
遇到了类似问题。只要账号密码登录
````
2023/01/23 13:09:31 Login Request: https://WEBVPN_URL:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs
panic: Not implemented auth: <?xml version="1.0" encoding="utf-8"?>
<Auth>
        <LBEnabled>0</LBEnabled>
        <Message>Auth is success </Message>
        <Result>1</Result>
        <TwfID>2b921673253cd7e8</TwfID>
        <pwpErrorCode>0</pwpErrorCode>
        <ErrorCode>1</ErrorCode>
        <CurAuth>1</CurAuth>
        <CSRF_RAND_CODE>141886837</CSRF_RAND_CODE>
        <EnableMAM>0</EnableMAM>
        <IsFirstAuth>1</IsFirstAuth>
        <AuthInfo><![CDATA[]]></AuthInfo>
</Auth>


goroutine 1 [running]:
main.WebLogin({0xc0000245e8?, 0x5?}, {0xc000022100, 0xa}, {0xc000022150, 0xa})
        C:/Users/sky96111/Desktop/EasierConnect/web_login.go:155 +0x18c5
main.main()
        C:/Users/sky96111/Desktop/EasierConnect/main.go:27 +0x4d7
````

**Comment by lyc8503** [comment]
各个不同版本的 EasyConnect 登录细节上有些差异, 我再调整一下.

**Comment by lyc8503** [comment]
@sky96111 @0neday 请测试一下 https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild9 是否解决了问题

**Comment by sky96111** [comment]
@lyc8503 谢谢,已可用. 新年快乐!

**Comment by lyc8503** [comment]
新年快乐!
